/**
 * IWA phrase expansion (v2.5.4) — re-exports generated RegExp[] from JSON phrase lists.
 * Regenerate: npx tsx scripts/build-iwa-phrase-regex.ts
 */
export {
  ACADEMIC_REGISTER_SIGNALS,
  ANALYTICAL_USE_SIGNALS,
  COLLOQUIAL_SEVERITY_2_PATTERNS,
  COLLOQUIAL_SEVERITY_3_PATTERNS,
  DESCRIPTIVE_LINKING_PATTERNS,
  DEVELOPING_COMMENTARY_PATTERNS,
  ECHO_PATTERNS,
  EVALUATIVE_LINKING_PATTERNS,
  EXPLORATORY_PATTERNS,
  HIGH_VALUE_CONTEXT_PATTERNS,
  JUNK_SOURCE_SIGNALS,
  LEVEL_1_INTEGRATION_PATTERNS,
  LEVEL_2_INTEGRATION_PATTERNS,
  MEDIUM_VALUE_CONTEXT_PATTERNS,
  PERSPECTIVE_ISOLATION_INDICATORS,
  STRONG_CITATION_SIGNALS,
  TANGENTIAL_STIMULUS_PATTERNS,
  THESIS_DETECTION_PATTERNS,
  TIER1_SOURCE_SIGNALS,
  TIER2_SOURCE_SIGNALS,
  TIER3_SOURCE_SIGNALS,
  WEAK_CITATION_SIGNALS,
  ZERO_VALUE_CONTEXT_PATTERNS,
} from "@/lib/seminar/seminarIwaPhrasePatterns.generated";
