/**
 * IRR phrase expansion (v2.5.5) — re-exports generated RegExp[] from JSON phrase lists.
 * Regenerate: npx tsx scripts/build-irr-phrase-regex.ts
 */
export {
  IRR_ACADEMIC_IRR_REGISTER_SIGNALS,
  IRR_ADEQUATE_ARGUMENT_SIGNALS,
  IRR_ADEQUATE_CONTEXT_SIGNALS,
  IRR_ADEQUATE_PERSPECTIVE_SIGNALS,
  IRR_ADEQUATE_SOURCE_EVALUATION_SIGNALS,
  IRR_INFORMAL_IRR_REGISTER_SIGNALS,
  IRR_STRONG_ARGUMENT_SIGNALS,
  IRR_STRONG_CONTEXT_SIGNALS,
  IRR_STRONG_IRR_CITATION_SIGNALS,
  IRR_STRONG_PERSPECTIVE_SIGNALS,
  IRR_STRONG_SOURCE_EVALUATION_SIGNALS,
  IRR_WEAK_ARGUMENT_SIGNALS,
  IRR_WEAK_CONTEXT_SIGNALS,
  IRR_WEAK_IRR_CITATION_SIGNALS,
  IRR_WEAK_PERSPECTIVE_SIGNALS,
  IRR_WEAK_SOURCE_EVALUATION_SIGNALS,
} from "@/lib/seminar/seminarIrrPhrasePatterns.generated";
