/**
 * Build RegExp[] exports from data/seminar/iwa-phrases/*.json
 * Run: npx tsx scripts/build-iwa-phrase-regex.ts
 */
import { readdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";
import { phraseToRegex } from "../lib/seminar/phraseToRegex";

const PHRASES_DIR = join(process.cwd(), "data/seminar/iwa-phrases");
const OUT_FILE = join(
  process.cwd(),
  "lib/seminar/seminarIwaPhrasePatterns.generated.ts",
);

function regexToSourceLiteral(re: RegExp): string {
  return `new RegExp(${JSON.stringify(re.source)}, ${JSON.stringify(re.flags)})`;
}

function main(): void {
  const files = readdirSync(PHRASES_DIR)
    .filter((f) => f.endsWith(".json"))
    .sort();

  if (files.length === 0) {
    throw new Error(`No JSON phrase files in ${PHRASES_DIR}`);
  }

  const lines: string[] = [
    "/**",
    " * AUTO-GENERATED by scripts/build-iwa-phrase-regex.ts — do not edit.",
    ` * Source: data/seminar/iwa-phrases/*.json (${files.length} categories)`,
    " */",
    "",
  ];

  for (const file of files) {
    const exportName = file.replace(/\.json$/, "");
    const raw = readFileSync(join(PHRASES_DIR, file), "utf8");
    const phrases: string[] = JSON.parse(raw);
    if (!Array.isArray(phrases)) {
      throw new Error(`${file}: expected JSON array`);
    }
    const patterns = phrases.map((p) => phraseToRegex(p));
    lines.push(`export const ${exportName}: RegExp[] = [`);
    for (const re of patterns) {
      lines.push(`  ${regexToSourceLiteral(re)},`);
    }
    lines.push("];");
    lines.push("");
  }

  writeFileSync(OUT_FILE, lines.join("\n"), "utf8");
  console.log(`Wrote ${OUT_FILE} (${files.length} exports)`);
}

main();
