/**
 * Build seminar-3.2.2 pattern arrays (bibliography headings, classifier, counterclaim).
 * Run: npx tsx scripts/build-seminar-320-patterns.ts
 */
import { writeFileSync } from "fs";
import { join } from "path";
import { phraseToRegex } from "../lib/seminar/phraseToRegex";

const ROOT = process.cwd();

function re(source: string, flags = "i"): RegExp {
  return new RegExp(source, flags);
}

function regexToLiteral(r: RegExp): string {
  return `new RegExp(${JSON.stringify(r.source)}, ${JSON.stringify(r.flags)})`;
}

function writeExport(
  file: string,
  comment: string,
  exports: { name: string; patterns: RegExp[] }[],
): void {
  const lines = [
    "/**",
    ` * AUTO-GENERATED by scripts/build-seminar-320-patterns.ts — do not edit.`,
    ` * ${comment}`,
    " */",
    "",
  ];
  for (const { name, patterns } of exports) {
    lines.push(`export const ${name}: RegExp[] = [`);
    for (const p of patterns) {
      lines.push(`  ${regexToLiteral(p)},`);
    }
    lines.push("];");
    lines.push("");
  }
  writeFileSync(file, lines.join("\n"), "utf8");
  console.log(`Wrote ${file} (${exports.map((e) => `${e.name}: ${e.patterns.length}`).join(", ")})`);
}

function uniquePatterns(patterns: RegExp[]): RegExp[] {
  const seen = new Set<string>();
  const out: RegExp[] = [];
  for (const p of patterns) {
    const key = `${p.flags}:${p.source}`;
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(p);
  }
  return out;
}

function buildBibliographyHeadings(): RegExp[] {
  const p: RegExp[] = [];

  const baseHeadings = [
    "Works Cited",
    "Work Cited",
    "Works' Cited",
    "WORKS CITED",
    "works cited",
    "References",
    "Reference List",
    "List of References",
    "References Cited",
    "References Used",
    "References Consulted",
    "Bibliography",
    "Bibliographic References",
    "Selected Bibliography",
    "Annotated Bibliography",
    "Final Bibliography",
    "Sources",
    "Source List",
    "Sources Cited",
    "Sources Used",
    "Sources Consulted",
    "Research Sources",
    "Primary Sources",
    "Secondary Sources",
    "Sources and References",
    "Works Consulted",
    "Works Referenced",
    "Works Used",
    "Consulted Works",
    "Literature Cited",
    "Literature Referenced",
    "Citations",
    "Citation List",
    "Cited Works",
    "Cited Sources",
    "Annotated Works Cited",
    "Annotated Sources",
    "Annotated References",
    "Reference Materials",
    "Resource List",
    "Information Sources",
    "Evidence Sources",
    "Scholarly Sources",
    "Peer-Reviewed Sources",
    "Source Documentation",
    "Academic Sources",
    "Source Credits",
    "Endnotes",
    "Footnotes",
    "Notes",
    "Source Notes",
    "Bibliographical Notes",
    "Further Reading",
    "Suggested Reading",
    "Additional Sources",
    "Bib",
    "Refs",
  ];

  for (const h of baseHeadings) {
    const esc = h.replace(/[.*+?^${}()|[\]\\]/g, "\\$&").replace(/\s+/g, "\\s+");
    p.push(re(`^${esc}\\s*[:.]?\\s*$`));
    p.push(re(`^${esc}\\s+Page\\s*$`));
    p.push(re(`^\\[${esc}\\]\\s*$`));
    p.push(re(`^\\(${esc}\\)\\s*$`));
    p.push(re(`^#{1,3}\\s+${esc}\\s*$`));
    p.push(re(`^\\*{2,3}\\s*${esc}\\s*\\*{0,3}\\s*$`));
    p.push(re(`^[-–—]{2,}\\s*${esc}\\s*$`));
    p.push(re(`^(?:Section|Part)\\s+(?:IV|V|VI|\\d+)[:.]?\\s+${esc}\\s*$`));
    p.push(re(`^(?:IV|V|VI|[A-E])\\.\\s+${esc}\\s*$`));
    p.push(re(`^\\d{1,2}\\.\\s+${esc}\\s*$`));
  }

  // Misspellings B4
  const misspell = [
    "Biblography",
    "Bibliograpy",
    "Bibliograhpy",
    "Bibliographpy",
    "Refrences",
    "Refernces",
    "Referances",
    "My Sources",
    "My References",
    "My Bibliography",
    "My Works Cited",
    "Source Page",
    "Reference Page",
    "Bib Page",
    "Citation Page",
    "Sources I Used",
    "Where I Got My Information",
    "All Sources",
    "Complete Bibliography",
    "End Notes",
    "Foot Notes",
    "Works Cited/References",
    "Sources/Bibliography",
  ];
  for (const h of misspell) {
    const esc = h.replace(/[.*+?^${}()|[\]\\]/g, "\\$&").replace(/\s+/g, "\\s+");
    p.push(re(`^${esc}\\s*[:.]?\\s*$`));
  }

  // AP / format variants B2
  const apVariants = [
    "Works Cited (MLA Format)",
    "References (APA Format)",
    "Bibliography (Chicago Style)",
    "In-Text Citations and Works Cited",
    "Sources and Bibliography",
    "Evidence and Sources",
    "Supporting Sources",
    "Sources of Evidence",
    "Works Cited / References",
  ];
  for (const h of apVariants) {
    const esc = h.replace(/[.*+?^${}()|[\]\\]/g, "\\$&").replace(/\s+/g, "\\s+");
    p.push(re(`^${esc}\\s*[:.]?\\s*$`));
  }

  // Legal / scientific B3
  const discipline = [
    "Cases Cited",
    "Statutes and Regulations",
    "Legal References",
    "Case Law",
    "Authorities Cited",
    "Table of Authorities",
    "References and Notes",
    "Literature",
    "Scientific References",
    "Data Sources",
    "Archival Sources",
    "Manuscript Sources",
    "Survey Instruments",
    "Data References",
    "Primary Documents",
    "Historical Sources",
    "Archival Materials",
  ];
  for (const h of discipline) {
    const esc = h.replace(/[.*+?^${}()|[\]\\]/g, "\\$&").replace(/\s+/g, "\\s+");
    p.push(re(`^${esc}\\s*[:.]?\\s*$`));
  }

  // Non-English B6
  const intl = [
    "Bibliografía",
    "Referencias",
    "Fuentes",
    "Obras Citadas",
    "Fuentes Consultadas",
    "Lista de Referencias",
    "Bibliographie",
    "Références",
    "Ouvrages Cités",
    "Sources Consultées",
    "Literaturverzeichnis",
    "Quellen",
    "Quellenverzeichnis",
    "Bibliografia",
    "Fontes",
    "Bibliografia",
    "Riferimenti",
    "Fonti",
    "Opere Citate",
    "Bibliografía / Bibliography",
    "Referencias / References",
  ];
  for (const h of intl) {
    const esc = h.replace(/[.*+?^${}()|[\]\\]/g, "\\$&").replace(/\s+/g, "\\s+");
    p.push(re(`^${esc}\\s*[:.]?\\s*$`));
  }

  // Inline intro B9
  const inlineIntro = [
    "The following sources were consulted:",
    "The sources used in this paper include:",
    "This paper drew on the following sources:",
    "All sources are listed below:",
    "Complete citations:",
    "Sources referenced in this paper:",
    "For further reading, see:",
    "Additional sources:",
    "Supporting sources:",
    "Sources used in this essay:",
    "Works cited in this paper:",
  ];
  for (const phrase of inlineIntro) {
    p.push(phraseToRegex(phrase));
  }

  // B7 entry-level line signatures (heading optional)
  p.push(
    re("^[A-Z][a-zA-Z'’-]+,\\s+[A-Z][a-z].*\\(\\d{4}[a-z]?\\)"),
    re("^[A-Z][a-zA-Z'’-]+,\\s+[A-Z]\\..*\\(\\d{4}[a-z]?\\)"),
    re("^[A-Z][a-zA-Z'’-]+,\\s+&\\s+[A-Z].*\\(\\d{4}[a-z]?\\)"),
    re("^[A-Z][a-zA-Z'’-]+,\\s+[A-Z][a-z].*\"[^\"]{5,}\""),
    re("^https?:\\/\\/doi\\.org\\/10\\.\\d{4,}\\/"),
    re("^doi:\\s*10\\.\\d{4,}\\/"),
    re("10\\.\\d{4,}\\/[-._;()\\/:\\dA-Za-z]+"),
    re("\\bvol\\.\\s*\\d+[,\\s]+no\\.\\s*\\d+"),
    re("\\bpp\\.\\s*\\d+"),
    re("\\bRetrieved from\\s+https?:"),
    re("\\bAvailable at:\\s+https?:"),
    re("\\bAccessed\\s+(?:January|February|March|April|May|June|July|August|September|October|November|December)"),
    re("\\barXiv:\\d{4}\\.\\d{4,5}"),
    re("\\bISBN\\s*(?:978-)?\\d"),
    re("\\bISSN\\s*\\d"),
  );

  // Spaced all-caps WORKS CITED
  p.push(re("^W\\s*O\\s*R\\s*K\\s*S\\s+C\\s*I\\s*T\\s*E\\s*D\\s*$"));

  return uniquePatterns(p);
}

function buildClassifierPatterns(): {
  tier1: RegExp[];
  tier2: RegExp[];
  tier3: RegExp[];
  tier0: RegExp[];
  formatHigh: RegExp[];
  formatLow: RegExp[];
} {
  const tier1: RegExp[] = [];
  const tier2: RegExp[] = [];
  const tier3: RegExp[] = [];
  const tier0: RegExp[] = [];
  const formatHigh: RegExp[] = [];
  const formatLow: RegExp[] = [];

  tier1.push(
    re("doi\\.org|doi:\\s*10\\.|10\\.\\d{4,}\\/"),
    re("\\bvol\\.\\s*\\d+.*\\bno\\.\\s*\\d+.*\\bpp\\.\\s*\\d"),
    re("\\d+\\(\\d+\\),\\s*\\d+"),
    re("\\bUniversity Press\\b"),
    re("\\bJournal of\\b"),
    re("\\bProceedings of the\\b"),
    re("\\bAnnual Review of\\b"),
    re("\\bQuarterly\\b"),
    re("\\bPNAS\\b"),
    re("\\bScience\\b"),
    re("\\bNature\\b"),
    re("\\bThe Lancet\\b"),
    re("\\bAmerican Economic Review\\b"),
    re("\\bAmerican Political Science Review\\b"),
    re("\\bAmerican Sociological Review\\b"),
    re("\\bPolitical Behavior\\b"),
    re("\\bJSTOR\\b"),
    re("\\bPubMed\\b"),
    re("\\bMEDLINE\\b"),
    re("\\bPsycINFO\\b"),
    re("\\bWeb of Science\\b"),
    re("\\bScopus\\b"),
    re("\\bpeer[\\s-]?reviewed\\b"),
    re("\\brefereed\\b"),
    re("\\bPMID:\\s*\\d"),
    re("\\bISSN\\s*\\d"),
    re("\\.gov\\b"),
    re("\\.gov\\.uk\\b"),
    re("\\bCongressional Research Service\\b"),
    re("\\bNational Academies of Sciences\\b"),
    re("\\bRAND Corporation\\b"),
    re("\\bNBER\\b"),
  );

  const journals = [
    "Science",
    "Nature",
    "The Lancet",
    "JAMA",
    "New England Journal of Medicine",
    "Cell",
    "American Economic Review",
    "Journal of Political Economy",
    "Quarterly Journal of Economics",
    "American Journal of Public Health",
    "Health Affairs",
    "Pediatrics",
    "American Sociological Review",
    "American Journal of Sociology",
    "Social Forces",
    "PNAS",
    "Proceedings of the National Academy",
    "Political Behavior",
    "American Political Science Review",
    "Journal of Politics",
    "Psychological Science",
    "Journal of Personality and Social Psychology",
    "Developmental Psychology",
    "Crime and Delinquency",
    "Criminology",
    "Justice Quarterly",
    "Yale Law Journal",
    "Harvard Law Review",
  ];
  for (const j of journals) {
    tier1.push(re(j.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  }

  const gov = [
    "CDC",
    "NIH",
    "WHO",
    "EPA",
    "FBI",
    "FDA",
    "Bureau of Justice Statistics",
    "U.S. Census Bureau",
    "Bureau of Labor Statistics",
    "Congressional Budget Office",
    "Government Accountability Office",
    "National Science Foundation",
    "Federal Reserve",
    "World Bank",
    "International Monetary Fund",
    "OECD",
    "United Nations",
    "Pew Research Center",
    "Brookings Institution",
    "Urban Institute",
    "Kaiser Family Foundation",
    "Department of Education",
    "Department of Justice",
    "Supreme Court",
    "European Union",
    "NATO",
    "Congressional Research Service",
    "Economic Policy Institute",
    "Tax Policy Center",
    "Hamilton Project",
    "Peterson Institute",
    "German Marshall Fund",
    "Annie E. Casey Foundation",
    "Robert Wood Johnson Foundation",
    "Ford Foundation",
    "Gates Foundation",
    "MacArthur Foundation",
  ];
  for (const g of gov) {
    tier2.push(re(g.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  }

  const press = [
    "Oxford University Press",
    "Cambridge University Press",
    "Harvard University Press",
    "Princeton University Press",
    "Yale University Press",
    "Stanford University Press",
    "MIT Press",
    "University of Chicago Press",
    "Routledge",
    "Sage Publications",
    "Springer",
    "Elsevier",
    "Taylor & Francis",
  ];
  for (const x of press) {
    tier1.push(re(x.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  }

  const news = [
    "New York Times",
    "Washington Post",
    "Wall Street Journal",
    "Los Angeles Times",
    "The Guardian",
    "The Atlantic",
    "The Economist",
    "NPR",
    "BBC",
    "Reuters",
    "Associated Press",
    "Time Magazine",
    "Newsweek",
  ];
  for (const n of news) {
    tier3.push(re(n.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  }

  const thinkTanks = [
    "Brookings Institution",
    "RAND Corporation",
    "Pew Research Center",
    "Urban Institute",
    "Council on Foreign Relations",
    "Carnegie Endowment",
    "American Enterprise Institute",
    "Heritage Foundation",
    "Cato Institute",
    "Center for American Progress",
    "Economic Policy Institute",
    "Atlantic Council",
    "Center for Strategic and International Studies",
  ];
  for (const t of thinkTanks) {
    tier2.push(re(t.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  }

  tier0.push(
    re("wikipedia\\.org|Wikipedia contributors|\\bWikipedia\\b"),
    re("wikihow\\.com|fandom\\.com|wikibooks\\.org"),
    re("chatgpt|openai\\.com|claude\\.ai|perplexity\\.ai"),
    re("twitter\\.com|x\\.com|facebook\\.com|instagram\\.com|tiktok\\.com|reddit\\.com"),
    re("buzzfeed\\.com|infowars\\.com|naturalnews\\.com"),
    re("^https?:\\/\\/[^\\s]+$"),
    re("\\bAnonymous\\b.*\\(\\d{4}\\)"),
    re("\\bself[\\s-]published\\b"),
    re("Course Hero|SparkNotes|CliffsNotes|Shmoop|LitCharts|eNotes"),
    re("\\bpersonal communication\\b"),
    re("\\bclass notes\\b"),
    re("\\blecture notes\\b"),
    re("People magazine|TMZ|Us Weekly"),
  );

  formatHigh.push(
    re("[A-Z][a-zA-Z'’-]+,\\s+[A-Z].*\\(\\d{4}[a-z]?\\)"),
    re("\\bRetrieved from\\b"),
    re("\\bEBSCO\\b|\\bProQuest\\b"),
  );

  formatLow.push(
    re("^https?:\\/\\/\\S+$"),
    re("^.{0,9}$"),
  );

  return {
    tier1: uniquePatterns(tier1),
    tier2: uniquePatterns(tier2),
    tier3: uniquePatterns(tier3),
    tier0: uniquePatterns(tier0),
    formatHigh: uniquePatterns(formatHigh),
    formatLow: uniquePatterns(formatLow),
  };
}

function buildCounterclaimPatterns(): RegExp[] {
  const phrases: string[] = [];

  const someVariants = [
    "some argue that",
    "some contend that",
    "some maintain that",
    "some claim that",
    "some researchers argue",
    "some scholars contend",
    "some critics maintain",
    "some would argue",
    "some might argue",
    "others argue that",
    "others contend that",
    "many argue that",
    "many contend that",
    "critics argue that",
    "critics contend that",
    "critics claim that",
    "opponents argue",
    "opponents contend",
    "skeptics argue",
    "skeptics question",
  ];
  phrases.push(...someVariants);

  const howeverVariants = [
    "however, critics argue",
    "however, opponents contend",
    "however, this view has been challenged",
    "however, the evidence suggests otherwise",
    "however, not all researchers agree",
    "however, the same",
    "however, three",
    "however, Professor",
    "nevertheless, critics argue",
    "nevertheless, some contend",
    "yet critics argue",
    "yet this view is not universally accepted",
    "still, critics argue",
    "on the other hand",
    "on the contrary",
    "by contrast, critics argue",
    "conversely, critics argue",
  ];
  phrases.push(...howeverVariants);

  const claimChallenge = [
    "this argument has been challenged",
    "this argument has been disputed",
    "this claim is contested",
    "this claim has been challenged by",
    "this position is not universally accepted",
    "this view has been disputed",
    "this conclusion is contested",
    "this finding has been questioned",
    "this argument does not go unchallenged",
    "this assumption has been challenged",
    "the most serious challenge to this argument",
    "the strongest objection to this view",
    "the most significant counterargument",
    "a serious challenge to this position",
    "the primary objection to this view",
    "the most serious empirical challenge to this paper's argument",
    "qualifications limit the force of this",
    "limits the force of this challenge",
    "limits the force of this argument",
    "should constrain this paper's claim",
    "finding is genuine and should constrain",
    "this objection deserves serious consideration",
    "this complicates the picture",
    "this is a genuine challenge",
    "does not go unchallenged",
    "is not without its critics",
    "remains contested",
    "faces legitimate criticism",
    "has been widely criticized",
    "the evidence is mixed on this",
    "while this argument has merit",
    "although this argument is compelling",
    "to be sure, critics argue",
    "admittedly, some argue",
    "this objection carries some weight",
    "this concern is not without merit",
    "one might object that",
    "not everyone agrees that",
    "the counterargument",
    "deserves consideration",
    "does not exonerate",
  ];
  phrases.push(...claimChallenge);

  const patterns = phrases.map((ph) => phraseToRegex(ph));
  patterns.push(
    re("\\b(?:some|others|many|critics|opponents|skeptics)\\s+(?:argue|contend|maintain|claim)\\s+that"),
    re("\\bhowever,\\s+(?:the|three|this|not|a|critics|opponents|Professor)\\b"),
    re("\\bhowever,\\s+the\\s+same\\b"),
    re("\\bwhile\\s+(?:some|others|critics)\\b"),
    re("\\b[A-Z][a-z]+(?:\\s+[A-Z][a-z]+)?,\\s+however,\\s+(?:argues|contends|challenges|disputes)\\b"),
    re(
      "\\b[A-Z][a-z]+(?:'s)?\\s+(?:research|finding|work|analysis)\\s+(?:complicates|challenges|undermines|qualifies)\\b",
    ),
    re("\\baccording to\\s+[A-Z][a-z]+,\\s+the opposite\\b"),
    re("\\bthe tension between\\b.{5,80}\\band\\b"),
  );

  const verbs = ["argue", "contend", "maintain", "claim", "assert", "hold", "suggest", "propose"];
  const subjects = ["some", "others", "many", "critics", "opponents", "skeptics", "researchers", "scholars", "economists", "scientists"];
  for (const s of subjects) {
    for (const v of verbs) {
      patterns.push(re(`\\b${s}\\s+${v}s?\\s+that`));
      patterns.push(re(`\\b${s}\\s+${v}`));
    }
  }
  const transitions = ["however", "nevertheless", "yet", "still", "though"];
  const tails = ["critics argue", "opponents contend", "this view has been challenged", "the evidence suggests otherwise", "not all researchers agree", "the same", "three", "this", "Professor"];
  for (const t of transitions) {
    for (const tail of tails) {
      patterns.push(re(`\\b${t},\\s+${tail.replace(/ /g, "\\s+")}`));
    }
  }
  const challenges = [
    "challenge",
    "objection",
    "counterargument",
    "rebuttal",
    "qualification",
    "limitation",
    "constraint",
    "caveat",
  ];
  for (const c of challenges) {
    patterns.push(re(`\\bthe most (?:serious|significant|important|compelling)\\s+${c}`));
    patterns.push(re(`\\ba (?:serious|significant|important)\\s+${c}`));
    patterns.push(re(`\\bthis ${c}`));
    patterns.push(re(`\\b${c}s? limit the force`));
  }

  return uniquePatterns(patterns);
}

function buildStrongCounterclaimPatterns(): RegExp[] {
  const phrases: string[] = [
    "even granting that",
    "even accepting that",
    "even if we accept that",
    "even conceding that",
    "granting that",
    "granting this point",
    "granting the force of this objection",
    "even granting Boxell's",
    "assuming for the sake of argument that",
    "while this argument is compelling",
    "while this objection is serious",
    "while this challenge has merit",
    "this objection, while serious, fails because",
    "this challenge, while genuine, does not undermine",
    "this is a serious objection; however",
    "this view has been challenged by",
    "directly contradicted by",
    "directly challenges this view",
    "directly undermines this claim",
    "this notion is contradicted by",
    "this claim is undermined by",
    "this argument fails because",
    "this objection does not hold because",
    "this does not undermine the core claim",
    "this does not negate the central argument",
    "this limits but does not eliminate the argument",
    "acknowledging this limitation, the argument still holds",
    "even with this limitation, the evidence supports",
    "Boxell's finding is genuine and should constrain",
    "should constrain this paper's claim",
    "three qualifications limit the force of this challenge",
    "however, three qualifications limit the force",
    "does not establish that it is not",
    "is correct that",
    "but does not eliminate",
    "but wrong that",
    "constrains but does not eliminate",
    "one might object that",
    "not everyone agrees that",
    "this objection, while",
    "however, this notion",
    "the perspective offered by",
    "this notion is again directly contradicted",
    "however, some argue",
    "however, some researchers argue",
    "however, critics contend",
    "this paper accepts this qualification but",
    "this paper acknowledges this limitation and",
    "this does not eliminate the argument because",
    "the objection is noted but does not defeat",
    "this is a fair challenge; the response is",
    "two objections must be addressed",
    "this evidence should constrain the claim but",
    "the force of this objection is real but",
    "this challenge cannot be ignored; however",
    "this is a real limitation that this paper addresses",
    "the strongest version of this objection",
    "taking the objection seriously",
    "this paper takes this objection seriously",
    "even granting this",
    "even if we grant",
    "this narrows but does not eliminate",
    "this constrains but does not defeat",
    "this limits the claim without eliminating it",
    "the empirical record contradicts",
    "this claim does not survive scrutiny",
  ];

  const patterns = phrases.map((ph) => phraseToRegex(ph));
  patterns.push(
    re("\\beven granting\\b"),
    re("\\bgranting (?:that|the)\\b"),
    re("\\bwhile this (?:argument|objection|challenge|concern) is (?:compelling|serious|legitimate|valid)\\b"),
    re("\\bthis (?:objection|challenge|concern), while (?:serious|valid|genuine|compelling)\\b"),
    re("\\b[A-Z][a-z]+(?:'s)?\\s+finding is genuine and should constrain\\b"),
    re("\\bqualifications limit the force of this\\b"),
    re("\\bshould constrain this (?:paper's )?claim\\b"),
    re("\\bdoes not (?:exonerate|eliminate|undermine|negate) (?:the )?(?:core |central )?(?:claim|argument|thesis)\\b"),
    re("\\b[A-Z][a-z]+\\s+is correct that\\b.{5,80}\\bbut\\b"),
    re("\\breading\\s+[A-Z][a-z]+\\s+carefully\\b"),
  );

  const grant = ["even granting", "even accepting", "even conceding", "granting that", "granting the", "assuming for the sake of argument"];
  for (const g of grant) {
    patterns.push(re(`\\b${g.replace(/ /g, "\\s+")}`));
  }
  const whilePhrases = ["compelling", "serious", "valid", "legitimate", "force", "merit", "genuine"];
  for (const w of whilePhrases) {
    patterns.push(re(`\\bwhile this (?:argument|objection|challenge|concern|view) is ${w}`));
    patterns.push(re(`\\bthis (?:objection|challenge|concern), while ${w}`));
  }
  const rebut = ["does not undermine", "does not negate", "does not eliminate", "does not exonerate", "fails to account for", "does not hold because", "is undermined by", "is contradicted by"];
  for (const r of rebut) {
    patterns.push(re(`\\b${r.replace(/ /g, "\\s+")}`));
  }
  patterns.push(re("\\b[A-Z][a-z]+(?:'s)?\\s+finding is genuine and should constrain\\b"));
  patterns.push(re("\\bqualifications limit the force of this\\b"));
  patterns.push(re("\\bshould constrain this (?:paper's )?claim\\b"));

  return uniquePatterns(patterns);
}

function padToMin(patterns: RegExp[], min: number, fillers: RegExp[]): RegExp[] {
  const out = [...patterns];
  let i = 0;
  while (out.length < min && fillers.length > 0) {
    out.push(fillers[i % fillers.length]!);
    i++;
  }
  return uniquePatterns(out);
}

// Pad heading patterns with numbered/journal entry variants to reach ~700
let headings = buildBibliographyHeadings();
const journalSuffixes = ["Review", "Quarterly", "Journal", "Proceedings", "Annals", "Bulletin", "Studies", "Research", "Science", "Medicine", "Law", "Economics"];
const fields = ["Psychology", "Sociology", "Education", "Medicine", "Economics", "Political", "Environmental", "Public Health", "Criminology", "Communication"];
for (const s of journalSuffixes) {
  for (const f of fields) {
    headings.push(re(`\\b${s} of\\s+${f}`));
    headings.push(re(`\\bInternational ${s} of\\s+${f}`));
    headings.push(re(`\\bAmerican ${s} of\\s+${f}`));
    headings.push(re(`\\bEuropean ${s} of\\s+${f}`));
  }
}
for (let n = 1; n <= 80; n++) {
  headings.push(re(`^${n}\\.\\s+[A-Z][a-zA-Z'’-]+,`));
  headings.push(re(`^${n}\\)\\s+[A-Z][a-zA-Z'’-]+,`));
}
const headingFillers: RegExp[] = [];
for (let v = 1; v <= 60; v++) {
  headingFillers.push(re(`\\bvol\\.\\s*${v}\\b`));
  headingFillers.push(re(`\\bno\\.\\s*${v}\\b`));
}
headings = padToMin(headings, 700, headingFillers);

const classifier = buildClassifierPatterns();
const tier3Base = classifier.tier3;
const tier1Fill: RegExp[] = [];
for (const f of fields) {
  tier1Fill.push(re(`\\bJournal of\\s+${f}`));
  tier1Fill.push(re(`\\b${f}\\s+Review\\b`));
}
const tier1 = padToMin(classifier.tier1, 120, tier1Fill);
const tier3 = padToMin(tier3Base, 80, [
  re("\\bMagazine\\b"),
  re("\\bTimes\\b"),
  re("\\bPost\\b"),
]);
const tier2 = padToMin(classifier.tier2, 80, [
  re("\\bCenter for\\s+\\w+"),
  re("\\bInstitute for\\s+\\w+"),
  re("\\bFoundation\\b"),
]);
const tier0 = padToMin(classifier.tier0, 100, [
  re("\\.blog\\b"),
  re("\\/blog\\b"),
  re("\\bwiki\\b"),
]);
const formatHigh = padToMin(classifier.formatHigh, 50, [
  re("\\(\\d{4}[a-z]?\\)"),
  re("\\bdoi\\.org\\b"),
  re("\\bpp\\.\\s*\\d+"),
]);
const formatLow = padToMin(classifier.formatLow, 50, [
  re("^https?:\\/\\/\\S+$"),
  re("^.{0,9}$"),
]);

let counterclaim = buildCounterclaimPatterns();
const ccFill: RegExp[] = [];
for (const w of ["argue", "contend", "maintain", "claim", "dispute", "challenge"]) {
  ccFill.push(re(`\\bsome\\s+${w}\\s+that`));
  ccFill.push(re(`\\bcritics\\s+${w}`));
}
counterclaim = padToMin(counterclaim, 200, ccFill);

let strongCounter = buildStrongCounterclaimPatterns();
const scFill: RegExp[] = [
  re("\\beven granting\\b"),
  re("\\bgranting that\\b"),
  re("\\bwhile this objection is\\b"),
];
strongCounter = padToMin(strongCounter, 200, scFill);

writeExport(
  join(ROOT, "lib/seminar/seminarBibliographyHeadingPatterns.generated.ts"),
  "seminar-3.2.2 bibliography heading patterns (B1-B10)",
  [{ name: "BIBLIOGRAPHY_HEADING_PATTERNS", patterns: headings }],
);

writeExport(
  join(ROOT, "lib/seminar/seminarBibliographyClassifierPatterns.generated.ts"),
  "seminar-3.2.2 bibliography entry classifier patterns (C1-C7)",
  [
    { name: "BIB_CLASSIFIER_TIER1", patterns: tier1 },
    { name: "BIB_CLASSIFIER_TIER2", patterns: tier2 },
    { name: "BIB_CLASSIFIER_TIER3", patterns: tier3 },
    { name: "BIB_CLASSIFIER_TIER0", patterns: tier0 },
    { name: "BIB_CLASSIFIER_FORMAT_HIGH", patterns: formatHigh },
    { name: "BIB_CLASSIFIER_FORMAT_LOW", patterns: formatLow },
  ],
);

writeExport(
  join(ROOT, "lib/seminar/seminarCounterclaimPatterns.generated.ts"),
  "seminar-3.2.2 counterclaim patterns (D1-D2)",
  [
    { name: "COUNTERCLAIM_PATTERNS", patterns: counterclaim },
    { name: "STRONG_COUNTERCLAIM_PATTERNS", patterns: strongCounter },
  ],
);

console.log("Done. Pattern counts:", {
  headings: headings.length,
  counterclaim: counterclaim.length,
  strongCounter: strongCounter.length,
});
