import { makeBand } from "@/lib/grader/format";
import type { CalibrationPaper } from "@/lib/grader/calibrationPapers";

export const EXTENDED_CALIBRATION_PAPERS: CalibrationPaper[] = [
  {
    id: "ap23-apc-research-sample-a",
    sampleLabel: "2023 Sample A",
    officialApScore: 5,
    title: "ap23-apc-research-sample-a.txt",
    discipline: "Official sample",
    features: {
      executedMethod: true,
      hasStudentData: true,
      litSynthesis: true,
      litIsolation: false,
      methodDefended: true,
      sophisticatedLimitations: false,
      practicalLimitationsOnly: false,
      strongImplications: false,
      statisticalAnalysis: false,
      gapExplicit: false,
      methodNotExecuted: false,
    },
    categoryAnchors: [
      makeBand(4, "Low"),
      makeBand(4, "Mid"),
      makeBand(3, "Mid"),
      makeBand(4, "High"),
      makeBand(5, "High"),
    ],
  },
  {
    id: "ap23-apc-research-sample-b",
    sampleLabel: "2023 Sample B",
    officialApScore: 5,
    title: "ap23-apc-research-sample-b.txt",
    discipline: "Official sample",
    features: {
      executedMethod: false,
      hasStudentData: false,
      litSynthesis: true,
      litIsolation: false,
      methodDefended: false,
      sophisticatedLimitations: false,
      practicalLimitationsOnly: false,
      strongImplications: false,
      statisticalAnalysis: true,
      gapExplicit: false,
      methodNotExecuted: false,
    },
    categoryAnchors: [
      makeBand(4, "Low"),
      makeBand(4, "Mid"),
      makeBand(2, "Low"),
      makeBand(1, "Low"),
      makeBand(5, "High"),
    ],
  },
  {
    id: "ap23-apc-research-sample-c",
    sampleLabel: "2023 Sample C",
    officialApScore: 4,
    title: "ap23-apc-research-sample-c.txt",
    discipline: "Official sample",
    features: {
      executedMethod: false,
      hasStudentData: false,
      litSynthesis: true,
      litIsolation: false,
      methodDefended: true,
      sophisticatedLimitations: false,
      practicalLimitationsOnly: true,
      strongImplications: false,
      statisticalAnalysis: false,
      gapExplicit: false,
      methodNotExecuted: false,
    },
    categoryAnchors: [
      makeBand(4, "Mid"),
      makeBand(4, "Low"),
      makeBand(4, "High"),
      makeBand(2, "Mid"),
      makeBand(5, "Mid"),
    ],
  },
  {
    id: "ap23-apc-research-sample-d",
    sampleLabel: "2023 Sample D",
    officialApScore: 4,
    title: "ap23-apc-research-sample-d.txt",
    discipline: "Official sample",
    features: {
      executedMethod: true,
      hasStudentData: true,
      litSynthesis: true,
      litIsolation: false,
      methodDefended: true,
      sophisticatedLimitations: false,
      practicalLimitationsOnly: true,
      strongImplications: false,
      statisticalAnalysis: false,
      gapExplicit: false,
      methodNotExecuted: false,
    },
    categoryAnchors: [
      makeBand(4, "Mid"),
      makeBand(2, "High"),
      makeBand(3, "Mid"),
      makeBand(4, "Low"),
      makeBand(5, "High"),
    ],
  },
  {
    id: "ap23-apc-research-sample-e",
    sampleLabel: "2023 Sample E",
    officialApScore: 3,
    title: "ap23-apc-research-sample-e.txt",
    discipline: "Official sample",
    features: {
      executedMethod: false,
      hasStudentData: false,
      litSynthesis: true,
      litIsolation: false,
      methodDefended: false,
      sophisticatedLimitations: false,
      practicalLimitationsOnly: false,
      strongImplications: false,
      statisticalAnalysis: false,
      gapExplicit: false,
      methodNotExecuted: false,
    },
    categoryAnchors: [
      makeBand(3, "Mid"),
      makeBand(3, "Low"),
      makeBand(3, "Mid"),
      makeBand(2, "Mid"),
      makeBand(4, "Mid"),
    ],
  },
  {
    id: "ap23-apc-research-sample-f",
    sampleLabel: "2023 Sample F",
    officialApScore: 3,
    title: "ap23-apc-research-sample-f.txt",
    discipline: "Official sample",
    features: {
      executedMethod: true,
      hasStudentData: true,
      litSynthesis: false,
      litIsolation: false,
      methodDefended: true,
      sophisticatedLimitations: false,
      practicalLimitationsOnly: true,
      strongImplications: false,
      statisticalAnalysis: false,
      gapExplicit: false,
      methodNotExecuted: false,
    },
    categoryAnchors: [
      makeBand(4, "Mid"),
      makeBand(2, "High"),
      makeBand(3, "Mid"),
      makeBand(3, "Mid"),
      makeBand(3, "Low"),
    ],
  },
  {
    id: "ap23-apc-research-sample-g",
    sampleLabel: "2023 Sample G",
    officialApScore: 2,
    title: "ap23-apc-research-sample-g.txt",
    discipline: "Official sample",
    features: {
      executedMethod: false,
      hasStudentData: false,
      litSynthesis: false,
      litIsolation: false,
      methodDefended: false,
      sophisticatedLimitations: false,
      practicalLimitationsOnly: false,
      strongImplications: false,
      statisticalAnalysis: false,
      gapExplicit: false,
      methodNotExecuted: false,
    },
    categoryAnchors: [
      makeBand(2, "Mid"),
      makeBand(1, "Low"),
      makeBand(1, "Low"),
      makeBand(1, "Low"),
      makeBand(1, "Low"),
    ],
  },
  {
    id: "ap23-apc-research-sample-h",
    sampleLabel: "2023 Sample H",
    officialApScore: 2,
    title: "ap23-apc-research-sample-h.txt",
    discipline: "Official sample",
    features: {
      executedMethod: false,
      hasStudentData: false,
      litSynthesis: false,
      litIsolation: false,
      methodDefended: false,
      sophisticatedLimitations: false,
      practicalLimitationsOnly: false,
      strongImplications: false,
      statisticalAnalysis: false,
      gapExplicit: false,
      methodNotExecuted: false,
    },
    categoryAnchors: [
      makeBand(3, "Mid"),
      makeBand(1, "Low"),
      makeBand(1, "Low"),
      makeBand(1, "Low"),
      makeBand(1, "Low"),
    ],
  },
  {
    id: "ap23-apc-research-sample-i",
    sampleLabel: "2023 Sample I",
    officialApScore: 1,
    title: "ap23-apc-research-sample-i.txt",
    discipline: "Official sample",
    features: {
      executedMethod: false,
      hasStudentData: false,
      litSynthesis: false,
      litIsolation: false,
      methodDefended: false,
      sophisticatedLimitations: false,
      practicalLimitationsOnly: false,
      strongImplications: false,
      statisticalAnalysis: false,
      gapExplicit: false,
      methodNotExecuted: false,
    },
    categoryAnchors: [
      makeBand(4, "Low"),
      makeBand(1, "Low"),
      makeBand(1, "Low"),
      makeBand(1, "Low"),
      makeBand(1, "Low"),
    ],
  },
  {
    id: "ap23-apc-research-sample-j",
    sampleLabel: "2023 Sample J",
    officialApScore: 1,
    title: "ap23-apc-research-sample-j.txt",
    discipline: "Official sample",
    features: {
      executedMethod: false,
      hasStudentData: false,
      litSynthesis: false,
      litIsolation: false,
      methodDefended: false,
      sophisticatedLimitations: false,
      practicalLimitationsOnly: false,
      strongImplications: false,
      statisticalAnalysis: false,
      gapExplicit: false,
      methodNotExecuted: false,
    },
    categoryAnchors: [
      makeBand(2, "Low"),
      makeBand(2, "Low"),
      makeBand(1, "Low"),
      makeBand(1, "Low"),
      makeBand(3, "Low"),
    ],
  },
  {
    id: "ap24-apc-research-sample-a",
    sampleLabel: "2024 Sample A",
    officialApScore: 5,
    title: "ap24-apc-research-sample-a.txt",
    discipline: "Official sample",
    features: {
      executedMethod: false,
      hasStudentData: false,
      litSynthesis: true,
      litIsolation: false,
      methodDefended: true,
      sophisticatedLimitations: false,
      practicalLimitationsOnly: true,
      strongImplications: false,
      statisticalAnalysis: true,
      gapExplicit: false,
      methodNotExecuted: false,
    },
    categoryAnchors: [
      makeBand(5, "High"),
      makeBand(3, "Mid"),
      makeBand(5, "High"),
      makeBand(3, "Mid"),
      makeBand(5, "High"),
    ],
  },
  {
    id: "ap24-apc-research-sample-b",
    sampleLabel: "2024 Sample B",
    officialApScore: 5,
    title: "ap24-apc-research-sample-b.txt",
    discipline: "Official sample",
    features: {
      executedMethod: false,
      hasStudentData: false,
      litSynthesis: true,
      litIsolation: false,
      methodDefended: true,
      sophisticatedLimitations: false,
      practicalLimitationsOnly: false,
      strongImplications: false,
      statisticalAnalysis: true,
      gapExplicit: false,
      methodNotExecuted: false,
    },
    categoryAnchors: [
      makeBand(5, "High"),
      makeBand(4, "Mid"),
      makeBand(4, "High"),
      makeBand(3, "Mid"),
      makeBand(5, "Mid"),
    ],
  },
  {
    id: "ap24-apc-research-sample-c",
    sampleLabel: "2024 Sample C",
    officialApScore: 4,
    title: "ap24-apc-research-sample-c.txt",
    discipline: "Official sample",
    features: {
      executedMethod: true,
      hasStudentData: true,
      litSynthesis: true,
      litIsolation: false,
      methodDefended: true,
      sophisticatedLimitations: false,
      practicalLimitationsOnly: false,
      strongImplications: false,
      statisticalAnalysis: true,
      gapExplicit: true,
      methodNotExecuted: false,
    },
    categoryAnchors: [
      makeBand(5, "High"),
      makeBand(4, "High"),
      makeBand(4, "High"),
      makeBand(5, "High"),
      makeBand(5, "High"),
    ],
  },
  {
    id: "ap24-apc-research-sample-d",
    sampleLabel: "2024 Sample D",
    officialApScore: 4,
    title: "ap24-apc-research-sample-d.txt",
    discipline: "Official sample",
    features: {
      executedMethod: true,
      hasStudentData: true,
      litSynthesis: true,
      litIsolation: false,
      methodDefended: true,
      sophisticatedLimitations: false,
      practicalLimitationsOnly: false,
      strongImplications: false,
      statisticalAnalysis: true,
      gapExplicit: false,
      methodNotExecuted: false,
    },
    categoryAnchors: [
      makeBand(5, "High"),
      makeBand(3, "Mid"),
      makeBand(5, "High"),
      makeBand(5, "Mid"),
      makeBand(5, "High"),
    ],
  },
  {
    id: "ap24-apc-research-sample-e",
    sampleLabel: "2024 Sample E",
    officialApScore: 3,
    title: "ap24-apc-research-sample-e.txt",
    discipline: "Official sample",
    features: {
      executedMethod: true,
      hasStudentData: true,
      litSynthesis: true,
      litIsolation: false,
      methodDefended: true,
      sophisticatedLimitations: false,
      practicalLimitationsOnly: false,
      strongImplications: false,
      statisticalAnalysis: false,
      gapExplicit: true,
      methodNotExecuted: false,
    },
    categoryAnchors: [
      makeBand(5, "High"),
      makeBand(4, "Low"),
      makeBand(3, "Mid"),
      makeBand(3, "Mid"),
      makeBand(4, "Mid"),
    ],
  },
  {
    id: "ap24-apc-research-sample-f",
    sampleLabel: "2024 Sample F",
    officialApScore: 3,
    title: "ap24-apc-research-sample-f.txt",
    discipline: "Official sample",
    features: {
      executedMethod: false,
      hasStudentData: false,
      litSynthesis: false,
      litIsolation: false,
      methodDefended: true,
      sophisticatedLimitations: false,
      practicalLimitationsOnly: false,
      strongImplications: false,
      statisticalAnalysis: false,
      gapExplicit: false,
      methodNotExecuted: false,
    },
    categoryAnchors: [
      makeBand(5, "High"),
      makeBand(1, "Low"),
      makeBand(4, "High"),
      makeBand(2, "Mid"),
      makeBand(1, "Low"),
    ],
  },
  {
    id: "ap24-apc-research-sample-g",
    sampleLabel: "2024 Sample G",
    officialApScore: 2,
    title: "ap24-apc-research-sample-g.txt",
    discipline: "Official sample",
    features: {
      executedMethod: false,
      hasStudentData: true,
      litSynthesis: false,
      litIsolation: false,
      methodDefended: true,
      sophisticatedLimitations: false,
      practicalLimitationsOnly: true,
      strongImplications: false,
      statisticalAnalysis: false,
      gapExplicit: false,
      methodNotExecuted: false,
    },
    categoryAnchors: [
      makeBand(5, "High"),
      makeBand(1, "Mid"),
      makeBand(3, "Mid"),
      makeBand(3, "Mid"),
      makeBand(3, "Mid"),
    ],
  },
  {
    id: "ap24-apc-research-sample-h",
    sampleLabel: "2024 Sample H",
    officialApScore: 2,
    title: "ap24-apc-research-sample-h.txt",
    discipline: "Official sample",
    features: {
      executedMethod: false,
      hasStudentData: false,
      litSynthesis: false,
      litIsolation: false,
      methodDefended: true,
      sophisticatedLimitations: false,
      practicalLimitationsOnly: false,
      strongImplications: false,
      statisticalAnalysis: false,
      gapExplicit: false,
      methodNotExecuted: false,
    },
    categoryAnchors: [
      makeBand(5, "High"),
      makeBand(1, "Low"),
      makeBand(4, "High"),
      makeBand(2, "Mid"),
      makeBand(1, "Low"),
    ],
  },
  {
    id: "ap24-apc-research-sample-i",
    sampleLabel: "2024 Sample I",
    officialApScore: 1,
    title: "ap24-apc-research-sample-i.txt",
    discipline: "Official sample",
    features: {
      executedMethod: false,
      hasStudentData: false,
      litSynthesis: false,
      litIsolation: false,
      methodDefended: false,
      sophisticatedLimitations: false,
      practicalLimitationsOnly: false,
      strongImplications: false,
      statisticalAnalysis: false,
      gapExplicit: false,
      methodNotExecuted: false,
    },
    categoryAnchors: [
      makeBand(5, "High"),
      makeBand(1, "Low"),
      makeBand(1, "Low"),
      makeBand(1, "Low"),
      makeBand(1, "Low"),
    ],
  },
  {
    id: "ap24-apc-research-sample-j",
    sampleLabel: "2024 Sample J",
    officialApScore: 1,
    title: "ap24-apc-research-sample-j.txt",
    discipline: "Official sample",
    features: {
      executedMethod: false,
      hasStudentData: false,
      litSynthesis: false,
      litIsolation: false,
      methodDefended: false,
      sophisticatedLimitations: false,
      practicalLimitationsOnly: false,
      strongImplications: false,
      statisticalAnalysis: false,
      gapExplicit: false,
      methodNotExecuted: false,
    },
    categoryAnchors: [
      makeBand(4, "High"),
      makeBand(1, "Low"),
      makeBand(1, "Low"),
      makeBand(1, "Low"),
      makeBand(1, "Low"),
    ],
  },
  {
    id: "ap25-apc-research-sample-a",
    sampleLabel: "2025 Sample A",
    officialApScore: 5,
    title: "ap25-apc-research-sample-a.txt",
    discipline: "Official sample",
    features: {
      executedMethod: true,
      hasStudentData: true,
      litSynthesis: true,
      litIsolation: false,
      methodDefended: false,
      sophisticatedLimitations: false,
      practicalLimitationsOnly: false,
      strongImplications: false,
      statisticalAnalysis: true,
      gapExplicit: false,
      methodNotExecuted: false,
    },
    categoryAnchors: [
      makeBand(5, "High"),
      makeBand(4, "High"),
      makeBand(4, "High"),
      makeBand(5, "Mid"),
      makeBand(5, "High"),
    ],
  },
  {
    id: "ap25-apc-research-sample-b",
    sampleLabel: "2025 Sample B",
    officialApScore: 5,
    title: "ap25-apc-research-sample-b.txt",
    discipline: "Official sample",
    features: {
      executedMethod: false,
      hasStudentData: false,
      litSynthesis: false,
      litIsolation: false,
      methodDefended: true,
      sophisticatedLimitations: false,
      practicalLimitationsOnly: false,
      strongImplications: false,
      statisticalAnalysis: false,
      gapExplicit: false,
      methodNotExecuted: false,
    },
    categoryAnchors: [
      makeBand(4, "Low"),
      makeBand(1, "High"),
      makeBand(4, "High"),
      makeBand(1, "Low"),
      makeBand(1, "Low"),
    ],
  },
  {
    id: "ap25-apc-research-sample-c",
    sampleLabel: "2025 Sample C",
    officialApScore: 4,
    title: "ap25-apc-research-sample-c.txt",
    discipline: "Official sample",
    features: {
      executedMethod: true,
      hasStudentData: true,
      litSynthesis: true,
      litIsolation: false,
      methodDefended: true,
      sophisticatedLimitations: false,
      practicalLimitationsOnly: false,
      strongImplications: false,
      statisticalAnalysis: false,
      gapExplicit: false,
      methodNotExecuted: false,
    },
    categoryAnchors: [
      makeBand(4, "Mid"),
      makeBand(4, "High"),
      makeBand(3, "Mid"),
      makeBand(4, "Low"),
      makeBand(5, "High"),
    ],
  },
  {
    id: "ap25-apc-research-sample-d",
    sampleLabel: "2025 Sample D",
    officialApScore: 4,
    title: "ap25-apc-research-sample-d.txt",
    discipline: "Official sample",
    features: {
      executedMethod: true,
      hasStudentData: true,
      litSynthesis: true,
      litIsolation: false,
      methodDefended: true,
      sophisticatedLimitations: false,
      practicalLimitationsOnly: false,
      strongImplications: false,
      statisticalAnalysis: false,
      gapExplicit: false,
      methodNotExecuted: false,
    },
    categoryAnchors: [
      makeBand(4, "Low"),
      makeBand(4, "Mid"),
      makeBand(5, "High"),
      makeBand(4, "Mid"),
      makeBand(5, "High"),
    ],
  },
  {
    id: "ap25-apc-research-sample-e",
    sampleLabel: "2025 Sample E",
    officialApScore: 3,
    title: "ap25-apc-research-sample-e.txt",
    discipline: "Official sample",
    features: {
      executedMethod: true,
      hasStudentData: true,
      litSynthesis: true,
      litIsolation: false,
      methodDefended: true,
      sophisticatedLimitations: false,
      practicalLimitationsOnly: true,
      strongImplications: true,
      statisticalAnalysis: true,
      gapExplicit: false,
      methodNotExecuted: false,
    },
    categoryAnchors: [
      makeBand(3, "Mid"),
      makeBand(3, "Low"),
      makeBand(5, "High"),
      makeBand(5, "Mid"),
      makeBand(4, "Mid"),
    ],
  },
  {
    id: "ap25-apc-research-sample-f",
    sampleLabel: "2025 Sample F",
    officialApScore: 3,
    title: "ap25-apc-research-sample-f.txt",
    discipline: "Official sample",
    features: {
      executedMethod: true,
      hasStudentData: true,
      litSynthesis: true,
      litIsolation: false,
      methodDefended: true,
      sophisticatedLimitations: false,
      practicalLimitationsOnly: false,
      strongImplications: false,
      statisticalAnalysis: false,
      gapExplicit: false,
      methodNotExecuted: false,
    },
    categoryAnchors: [
      makeBand(5, "High"),
      makeBand(4, "Mid"),
      makeBand(1, "Low"),
      makeBand(3, "Mid"),
      makeBand(5, "High"),
    ],
  },
  {
    id: "ap25-apc-research-sample-g",
    sampleLabel: "2025 Sample G",
    officialApScore: 2,
    title: "ap25-apc-research-sample-g.txt",
    discipline: "Official sample",
    features: {
      executedMethod: false,
      hasStudentData: false,
      litSynthesis: true,
      litIsolation: false,
      methodDefended: false,
      sophisticatedLimitations: false,
      practicalLimitationsOnly: false,
      strongImplications: false,
      statisticalAnalysis: false,
      gapExplicit: false,
      methodNotExecuted: false,
    },
    categoryAnchors: [
      makeBand(4, "Low"),
      makeBand(1, "Low"),
      makeBand(3, "Mid"),
      makeBand(1, "Low"),
      makeBand(3, "Low"),
    ],
  },
  {
    id: "ap25-apc-research-sample-h",
    sampleLabel: "2025 Sample H",
    officialApScore: 2,
    title: "ap25-apc-research-sample-h.txt",
    discipline: "Official sample",
    features: {
      executedMethod: false,
      hasStudentData: false,
      litSynthesis: true,
      litIsolation: false,
      methodDefended: false,
      sophisticatedLimitations: false,
      practicalLimitationsOnly: true,
      strongImplications: false,
      statisticalAnalysis: false,
      gapExplicit: false,
      methodNotExecuted: true,
    },
    categoryAnchors: [
      makeBand(4, "Mid"),
      makeBand(2, "Mid"),
      makeBand(1, "Low"),
      makeBand(1, "Low"),
      makeBand(3, "Low"),
    ],
  },
  {
    id: "ap25-apc-research-sample-i",
    sampleLabel: "2025 Sample I",
    officialApScore: 1,
    title: "ap25-apc-research-sample-i.txt",
    discipline: "Official sample",
    features: {
      executedMethod: false,
      hasStudentData: false,
      litSynthesis: false,
      litIsolation: false,
      methodDefended: false,
      sophisticatedLimitations: false,
      practicalLimitationsOnly: false,
      strongImplications: false,
      statisticalAnalysis: false,
      gapExplicit: false,
      methodNotExecuted: false,
    },
    categoryAnchors: [
      makeBand(4, "Low"),
      makeBand(2, "Low"),
      makeBand(1, "Low"),
      makeBand(1, "Low"),
      makeBand(1, "Low"),
    ],
  },
  {
    id: "ap25-apc-research-sample-j",
    sampleLabel: "2025 Sample J",
    officialApScore: 1,
    title: "ap25-apc-research-sample-j.txt",
    discipline: "Official sample",
    features: {
      executedMethod: false,
      hasStudentData: false,
      litSynthesis: false,
      litIsolation: false,
      methodDefended: false,
      sophisticatedLimitations: false,
      practicalLimitationsOnly: false,
      strongImplications: false,
      statisticalAnalysis: false,
      gapExplicit: false,
      methodNotExecuted: false,
    },
    categoryAnchors: [
      makeBand(4, "Low"),
      makeBand(1, "Low"),
      makeBand(1, "Low"),
      makeBand(1, "Low"),
      makeBand(1, "Low"),
    ],
  },
];
